language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

before_script:
  - composer install --dev

script:
  - ./vendor/bin/phpunit

notifications:
  email:
    recipients:
      - david.verholen@brandung.de
    on_success: never
    on_failure: always
